version: '3.8'

services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    environment:
      - SERVICES=sqs
      - DEFAULT_REGION=us-east-1
    ports:
      - "4566:4566" 
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - mynetwork

  postgres-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: fiap
      POSTGRES_PASSWORD: fiap@123
      POSTGRES_DB: pedidos_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mynetwork

  pedidos_microservice:
    image: pedidos_microservice
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres-db
      - localstack
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__PostgresConnection=Host=postgres-db;Port=5432;Database=pedidos_db;Username=fiap;Password=fiap@123
      - SQS_ENDPOINT=http://localstack:4566
    networks:
      - mynetwork

volumes:
  postgres_data:

networks:
  mynetwork:
    driver: bridge